export const NEW_CONTACT_REQUEST = "NEW_CONTACT_REQUEST";
export const NEW_CONTACT_SUCCESS = "NEW_CONTACT_SUCCESS";
export const NEW_CONTACT_FAIL = "NEW_CONTACT_FAIL";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

export const ALL_CONTACTS_REQUEST = "ALL_CONTACTS_REQUEST";
export const ALL_CONTACTS_SUCCESS = "ALL_CONTACTS_SUCCESS";
export const ALL_CONTACTS_FAIL = "ALL_CONTACTS_FAIL";  

export const CLEAR_ERRORS = "CLEAR_ERRORS";
